import * as fs from 'node:fs';
import * as path from 'node:path';
import type {DesignTokens} from './types';

export function ensureDir(dir: string): void {
	fs.mkdirSync(dir, {recursive: true});
}

export function writeFile(filePath: string, content: string): void {
	ensureDir(path.dirname(filePath));
	fs.writeFileSync(filePath, content, 'utf8');
}

export function tokensToJson(tokens: DesignTokens): string {
	return JSON.stringify(tokens, null, 2);
}

export function tokensToCssVars(tokens: DesignTokens): string {
	const lines: string[] = [':root {'];

	// Custom properties from source
	for (const [k, v] of Object.entries(tokens.customProperties).slice(0, 80)) {
		lines.push(`  ${k}: ${v};`);
	}

	// Generated token vars
	tokens.colors.all.slice(0, 10).forEach((c, i) => {
		lines.push(`  --color-${i + 1}: ${c};`);
	});
	tokens.typography.fontFamilies.slice(0, 3).forEach((f, i) => {
		lines.push(`  --font-family-${i + 1}: ${JSON.stringify(f)}, sans-serif;`);
	});
	tokens.typography.fontSizes.slice(0, 8).forEach((s, i) => {
		lines.push(`  --font-size-${i + 1}: ${s};`);
	});
	tokens.spacing.slice(0, 10).forEach((s, i) => {
		lines.push(`  --spacing-${i + 1}: ${s};`);
	});
	tokens.borderRadius.slice(0, 5).forEach((r, i) => {
		lines.push(`  --radius-${i + 1}: ${r};`);
	});

	lines.push('}');
	return lines.join('\n');
}

export function tokensToScss(tokens: DesignTokens): string {
	const lines: string[] = ['// Generated by designlang', ''];

	lines.push('// Colors');
	tokens.colors.all.slice(0, 12).forEach((c, i) => {
		lines.push(`$color-${i + 1}: ${c};`);
	});

	lines.push('');
	lines.push('// Typography');
	tokens.typography.fontFamilies.slice(0, 3).forEach((f, i) => {
		lines.push(`$font-family-${i + 1}: ${JSON.stringify(f)}, sans-serif;`);
	});
	tokens.typography.fontSizes.slice(0, 8).forEach((s, i) => {
		lines.push(`$font-size-${i + 1}: ${s};`);
	});

	lines.push('');
	lines.push('// Spacing');
	tokens.spacing.slice(0, 10).forEach((s, i) => {
		lines.push(`$spacing-${i + 1}: ${s};`);
	});

	lines.push('');
	lines.push('// Border Radius');
	tokens.borderRadius.slice(0, 5).forEach((r, i) => {
		lines.push(`$radius-${i + 1}: ${r};`);
	});

	return lines.join('\n');
}

export function tokensTailwindConfig(tokens: DesignTokens): string {
	const colors: Record<string, string> = {};
	tokens.colors.all.slice(0, 10).forEach((c, i) => {
		colors[`brand-${i + 1}`] = c;
	});

	const fontFamily: Record<string, string[]> = {};
	tokens.typography.fontFamilies.slice(0, 2).forEach((f, i) => {
		const key = i === 0 ? 'sans' : `font-${i + 1}`;
		fontFamily[key] = [f, 'sans-serif'];
	});

	const borderRadius: Record<string, string> = {};
	tokens.borderRadius.slice(0, 4).forEach((r, i) => {
		borderRadius[`brand-${i + 1}`] = r;
	});

	const config = {
		theme: {
			extend: {
				colors,
				fontFamily,
				borderRadius,
			},
		},
	};

	return `/** @type {import('tailwindcss').Config} */\nmodule.exports = ${JSON.stringify(config, null, 2)};\n`;
}
