import chalk from 'chalk';
import * as path from 'node:path';
import * as fs from 'node:fs';
import {fetchDesign} from '../fetcher';
import {parseCss} from '../css-parser';
import {generateCloneScaffold} from '../ai';
import {tokensToCssVars, tokensTailwindConfig, writeFile} from '../output';

const FILE_DELIMITER = /^=== (.+?) ===$/m;

function splitScaffold(raw: string): Array<{name: string; content: string}> {
	const parts = raw.split(/^=== .+? ===$\n?/m);
	const names = [...raw.matchAll(/^=== (.+?) ===/gm)].map((m) => m[1] ?? '');
	return names.map((name, i) => ({name, content: (parts[i + 1] ?? '').trim()}));
	void FILE_DELIMITER;
}

function basicScaffold(domain: string, cssVars: string, twConfig: string): Array<{name: string; content: string}> {
	return [
		{
			name: 'app/globals.css',
			content: cssVars + '\n\n@tailwind base;\n@tailwind components;\n@tailwind utilities;\n',
		},
		{
			name: 'app/layout.tsx',
			content: `import type {Metadata} from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: '${domain}',
  description: 'Design clone of ${domain}',
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`,
		},
		{
			name: 'app/page.tsx',
			content: `export default function Home() {
  return (
    <main className="min-h-screen">
      <section className="flex flex-col items-center justify-center min-h-screen gap-8 p-8">
        <h1 className="text-4xl font-bold">${domain}</h1>
        <p className="text-lg text-gray-600 max-w-prose text-center">
          A Next.js clone scaffolded from the design tokens of ${domain}.
        </p>
        <a href="#" className="btn">Get started</a>
      </section>
    </main>
  );
}
`,
		},
		{name: 'tailwind.config.ts', content: twConfig},
		{
			name: 'package.json',
			content: JSON.stringify(
				{
					name: `${domain}-clone`,
					version: '0.1.0',
					scripts: {dev: 'next dev', build: 'next build', start: 'next start'},
					dependencies: {next: '^14.0.0', react: '^18.0.0', 'react-dom': '^18.0.0'},
					devDependencies: {
						typescript: '^5.0.0',
						'@types/react': '^18.0.0',
						tailwindcss: '^3.0.0',
						autoprefixer: '^10.0.0',
					},
				},
				null,
				2,
			),
		},
		{
			name: 'README.md',
			content: `# ${domain} Clone\n\nNext.js scaffold generated by [designlang](https://github.com/remotion-dev/remotion).\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n`,
		},
	];
}

export async function runClone(targetUrl: string): Promise<void> {
	console.log(chalk.cyan(`Fetching ${targetUrl}…`));
	const design = await fetchDesign(targetUrl);
	const tokens = parseCss(design.css, design.baseUrl, design.domain);
	const outDir = `designlang-clone-${tokens.domain}`;

	let files: Array<{name: string; content: string}>;

	if (process.env['ANTHROPIC_API_KEY']) {
		console.log(chalk.cyan('Generating Next.js scaffold via Claude…'));
		console.log(chalk.dim('  (This may take 30-60 seconds)'));
		try {
			const raw = await generateCloneScaffold(tokens);
			files = splitScaffold(raw);
			if (files.length === 0) {
				throw new Error('No files parsed from AI response');
			}
		} catch {
			console.log(chalk.yellow('  Falling back to template scaffold'));
			files = basicScaffold(
				tokens.domain,
				tokensToCssVars(tokens),
				tokensTailwindConfig(tokens),
			);
		}
	} else {
		console.log(chalk.dim('  ANTHROPIC_API_KEY not set — using template scaffold'));
		files = basicScaffold(
			tokens.domain,
			tokensToCssVars(tokens),
			tokensTailwindConfig(tokens),
		);
	}

	for (const {name, content} of files) {
		const filePath = path.join(outDir, name);
		fs.mkdirSync(path.dirname(filePath), {recursive: true});
		writeFile(filePath, content);
	}

	console.log(
		chalk.green(`\n✓ Next.js starter scaffolded for ${tokens.domain}`),
	);
	console.log(chalk.bold(`\n🚀 Output: ./${outDir}/`));
	console.log(chalk.dim('\n  cd ' + outDir + ' && npm install && npm run dev'));
}
