import chalk from 'chalk';
import * as path from 'node:path';
import {fetchDesign} from '../fetcher';
import {parseCss} from '../css-parser';
import {
	tokensToJson,
	tokensToCssVars,
	tokensToScss,
	tokensTailwindConfig,
	writeFile,
} from '../output';

function generateReadme(domain: string): string {
	return `# Design System — ${domain}

Generated by [designlang](https://github.com/remotion-dev/remotion).

## Files

| File | Description |
|------|-------------|
| \`tokens.json\` | All design tokens as JSON |
| \`tokens.css\` | CSS custom properties (\`:root\` block) |
| \`tokens.scss\` | SCSS variables |
| \`tailwind.config.js\` | Tailwind CSS configuration extension |
| \`typography.css\` | Typography utility classes |
| \`components/\` | Basic component styles |

## Usage

### CSS Custom Properties
\`\`\`html
<link rel="stylesheet" href="tokens.css">
\`\`\`

### SCSS
\`\`\`scss
@import 'tokens';
\`\`\`

### Tailwind
Copy \`tailwind.config.js\` to your project root and merge with your existing config.
`;
}

function generateTypographyCss(domain: string, fontFamilies: string[], fontSizes: string[]): string {
	const primaryFont = fontFamilies[0] ?? 'system-ui';
	const secondaryFont = fontFamilies[1] ?? fontFamilies[0] ?? 'system-ui';
	const sizes = fontSizes.slice(0, 8);

	return `/* Typography — ${domain} */

body {
  font-family: ${JSON.stringify(primaryFont)}, system-ui, -apple-system, sans-serif;
  line-height: 1.5;
}

h1, h2, h3, h4, h5, h6 {
  font-family: ${JSON.stringify(secondaryFont)}, system-ui, -apple-system, sans-serif;
  line-height: 1.2;
  font-weight: 700;
}

${sizes.map((s, i) => `.text-${i + 1} { font-size: ${s}; }`).join('\n')}
`;
}

function generateComponentsCss(domain: string): string {
	return `/* Components — ${domain} */

.btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  padding: var(--spacing-2, 0.5rem) var(--spacing-4, 1rem);
  border-radius: var(--radius-1, 4px);
  background: var(--color-1, #0070f3);
  color: #fff;
  font-family: inherit;
  font-size: var(--font-size-1, 1rem);
  font-weight: 600;
  cursor: pointer;
  border: none;
  text-decoration: none;
  transition: opacity 0.15s;
}

.btn:hover { opacity: 0.85; }

.card {
  border-radius: var(--radius-1, 8px);
  box-shadow: var(--shadow-1, 0 1px 3px rgba(0,0,0,.12));
  padding: var(--spacing-4, 1.5rem);
  background: #fff;
}

.badge {
  display: inline-block;
  padding: 0.125rem 0.5rem;
  border-radius: var(--radius-1, 999px);
  font-size: var(--font-size-1, 0.75rem);
  font-weight: 500;
  background: var(--color-2, #f0f0f0);
}
`;
}

export async function runPack(targetUrl: string): Promise<void> {
	console.log(chalk.cyan(`Fetching ${targetUrl}…`));
	const design = await fetchDesign(targetUrl);
	console.log(chalk.cyan('Extracting design tokens…'));
	const tokens = parseCss(design.css, design.baseUrl, design.domain);

	const outDir = `designlang-pack-${tokens.domain}`;
	const files: Array<[string, string]> = [
		[path.join(outDir, 'tokens.json'), tokensToJson(tokens)],
		[path.join(outDir, 'tokens.css'), tokensToCssVars(tokens)],
		[path.join(outDir, 'tokens.scss'), tokensToScss(tokens)],
		[path.join(outDir, 'tailwind.config.js'), tokensTailwindConfig(tokens)],
		[
			path.join(outDir, 'typography.css'),
			generateTypographyCss(
				tokens.domain,
				tokens.typography.fontFamilies,
				tokens.typography.fontSizes,
			),
		],
		[
			path.join(outDir, 'components', 'base.css'),
			generateComponentsCss(tokens.domain),
		],
		[path.join(outDir, 'README.md'), generateReadme(tokens.domain)],
	];

	for (const [filePath, content] of files) {
		writeFile(filePath, content);
	}

	console.log(
		chalk.green(`\n✓ Design system packed for ${tokens.domain}`),
	);
	console.log(
		chalk.dim(
			`  ${files.length} files written`,
		),
	);
	console.log(chalk.bold(`\n📦 Output: ./${outDir}/`));
	console.log(chalk.dim('  tokens.json  tokens.css  tokens.scss  tailwind.config.js'));
	console.log(chalk.dim('  typography.css  components/base.css  README.md'));
}
